"""Password hashing, session signing, and API-key encryption helpers."""

from __future__ import annotations

import base64
import hashlib
import hmac
import secrets
from typing import Final

from cryptography.fernet import Fernet, InvalidToken
from itsdangerous import BadSignature, URLSafeTimedSerializer


SCRYPT_N: Final[int] = 2**14
SCRYPT_R: Final[int] = 8
SCRYPT_P: Final[int] = 1


def hash_password(password: str) -> str:
    """Hash an admin password with a per-password scrypt salt."""
    salt = secrets.token_bytes(16)
    digest = hashlib.scrypt(
        password.encode("utf-8"),
        salt=salt,
        n=SCRYPT_N,
        r=SCRYPT_R,
        p=SCRYPT_P,
    )
    encode = lambda value: base64.urlsafe_b64encode(value).decode("ascii")
    return f"scrypt${SCRYPT_N}${SCRYPT_R}${SCRYPT_P}${encode(salt)}${encode(digest)}"


def verify_password(password: str, encoded: str) -> bool:
    """Verify the password format generated by hash_password."""
    try:
        algorithm, n, r, p, salt_text, digest_text = encoded.split("$", 5)
        if algorithm != "scrypt":
            return False
        salt = base64.urlsafe_b64decode(salt_text.encode("ascii"))
        expected = base64.urlsafe_b64decode(digest_text.encode("ascii"))
        actual = hashlib.scrypt(
            password.encode("utf-8"),
            salt=salt,
            n=int(n),
            r=int(r),
            p=int(p),
        )
        return hmac.compare_digest(actual, expected)
    except (ValueError, TypeError):
        return False


class SecretBox:
    """Encrypt API keys at rest using a Fernet master key."""

    def __init__(self, master_key: str) -> None:
        if not master_key:
            raise ValueError("MASTER_KEY is required")
        try:
            self._fernet = Fernet(master_key.encode("ascii"))
        except (ValueError, TypeError) as exc:
            raise ValueError("MASTER_KEY must be a valid Fernet key") from exc

    def encrypt(self, value: str) -> str:
        return self._fernet.encrypt(value.encode("utf-8")).decode("ascii")

    def decrypt(self, value: str) -> str:
        try:
            return self._fernet.decrypt(value.encode("ascii")).decode("utf-8")
        except (InvalidToken, ValueError, TypeError) as exc:
            raise ValueError("Stored API key could not be decrypted") from exc


class SessionAuth:
    """Signed, expiring cookie sessions for the admin-only panel."""

    cookie_name = "ai_balancer_session"

    def __init__(self, secret: str, admin_password_hash: str) -> None:
        if not secret or not admin_password_hash:
            raise ValueError("SESSION_SECRET and ADMIN_PASSWORD_HASH are required")
        self._serializer = URLSafeTimedSerializer(secret, salt="ai-balancer-session")
        self._admin_password_hash = admin_password_hash

    def authenticate(self, password: str) -> bool:
        return verify_password(password, self._admin_password_hash)

    def create(self) -> str:
        return self._serializer.dumps({"role": "admin"})

    def is_valid(self, token: str | None, max_age: int = 60 * 60 * 24) -> bool:
        if not token:
            return False
        try:
            data = self._serializer.loads(token, max_age=max_age)
            return data.get("role") == "admin"
        except BadSignature:
            return False